### ISSUE TITLE
What are the risks?

### ISSUE THREAD

**Issue by LeifAndersen** [flomlo/rm2canvas#1]
In your installation section you say:

> If using a rm2: Place the screenshotter GO programm (see https://gist.github.com/owulveryck/4007cbf14e0028f373e4294f66c4ad07) in /home/root/screenshot.arm on your device. Warning: Please be aware of the risks. If using a rm1: TODO (should be quite risk free, just read /dev/fb0?)

But I can't find anywhere in this repo, or the linked gist, that says what risks you are referring to.

Is it just the destroying the eink display issue (related to the prevent-frying-pan kernel module?) or are you referring to something else?

**Comment by flomlo** [comment]
Hi,

I do think that the risks are moderately minimal.
But you are running `go` code accessing (not writing to, as far as I understand) memory pages with root rights on a device which is rather hard to reset. As far as I understand the precise location of the memory pages changes occasionally with each software update.

Personally I would try to be careful when there are major updates of `xochitl`. You probably have to update the code then.

I closely follow current development on that front, but I can't promise that I'll update the code instantly :D  


So yeah, this is the risk I meant. Maybe I'm just a little bit too careful with my new toy ;)

**Comment by flomlo** [comment]
I've updated the readme a little bit to make it clearer.

Does this answer your original question?

**Comment by LeifAndersen** [comment]
OHH, those are the risks you meant. Okay then. This clears things up a bit.

> So yeah, this is the risk I meant. Maybe I'm just a little bit too careful with my new toy ;)

Nah, I am too. ;)

Anyway, thanks for clearing that up.
